[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https: data: blob: 'unsafe-inline' 'unsafe-eval'; connect-src 'self' https: wss: data: blob:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' data: https:; media-src 'self' data: https:; worker-src 'self' blob:;"

[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://eijkjrlajylvmqkbqgdq.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpamtqcmxhanlsdm1xa2JxZ2RxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzOTI5NDksImV4cCI6MjA1NDk2ODk0OX0.uHXRj2n2mOY7m8oKDglbaFPQmE52HnGawp0aPrhO_9c"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs" 